# Generated by Django 4.2.7 on 2023-11-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('vl_transacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nu_conta_pagador', models.CharField(max_length=20)),
                ('nu_conta_beneficiario', models.CharField(max_length=20)),
                ('dt_transacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
